{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.mariadbPassword }}
  rootpass: {{ .Values.mariadbPassword | b64enc | quote }}
  {{ else }}
  rootpass: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- end }}
