{{- if and (.Values.ingress.enabled) (eq true .Values.ingress.traefik.enabled) }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "dokuwiki.names.fullname" . }}-http
  labels: 
    {{- include "dokuwiki.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.traefik.entryPointName.http }}
  routes:
  {{- if .Values.ingress.hostname }}
  - match: Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
  {{- else }}
  - match: PathPrefix(`{{ .Values.ingress.path }}`)
  {{- end }}
    kind: Rule
    {{- if .Values.ingress.traefik.tls.enabled }}
    middlewares:
      - name: {{ template "dokuwiki.names.fullname" . }}-redirect-to-https
    {{- end }}
    services:
    - name: {{ template "dokuwiki.names.fullname" . }}
      port: {{ .Values.service.ports.http }}
{{- if .Values.ingress.traefik.tls.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "dokuwiki.names.fullname" . }}-https
  labels: 
    {{- include "dokuwiki.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.traefik.entryPointName.https }}
  routes:
  {{- if .Values.ingress.hostname }}
  - match: Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
  {{- else }}
  - match: PathPrefix(`{{ .Values.ingress.path }}`)
  {{- end }}
    kind: Rule
    services:
    - name: {{ template "dokuwiki.names.fullname" . }}
      port: {{ .Values.service.ports.http }}
  tls:
    certResolver: {{ .Values.ingress.traefik.tls.certResolver }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ template "dokuwiki.names.fullname" . }}-redirect-to-https
  labels: 
    {{- include "dokuwiki.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
{{- end }}