{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{- .Values.fullname | trunc 63 | trimSuffix "-" -}}
  labels:
    app.kubernetes.io/name: {{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
    helm.sh/chart: {{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.dokuwikiPassword }}
  dokuwiki-password: {{ .Values.dokuwikiPassword | b64enc | quote }}
  {{ else }}
  dokuwiki-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- end }}
