{{- if and (.Values.ingress.enabled) (eq true .Values.ingress.traefik.enabled) }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "owncloud.fullname" . }}
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.traefik.entryPointName.http }}
  {{- if .Values.ingress.traefik.tls.enabled }}
    - {{ .Values.ingress.traefik.entryPointName.https }}
  {{- end }}
  routes:
  {{- if .Values.ingress.hostname }}
  - match: Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
  {{- else }}
  - match: PathPrefix(`{{ .Values.ingress.path }}`)
  {{- end }}
    kind: Rule
    services:
    - name: {{ include "owncloud.fullname" . }}
      port: {{ .Values.service.port }}
  {{- if .Values.ingress.traefik.tls.enabled }}
  tls:
    certResolver: {{ .Values.ingress.traefik.tls.certResolver }}
  {{- end }}
{{- end }}
