{{- if .Values.persistence.owncloud.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "owncloud.fullname" . }}
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  nfs:
    server: {{ .Values.persistence.owncloud.nfs.server }}
    path: {{ .Values.persistence.owncloud.nfs.path }}
{{end}}
---
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim ) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "owncloud.fullname" . }}
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- if not (empty .Values.persistence.accessModes) }}
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.persistence.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass }}
  selector: 
    matchLabels:
      {{- include "mariadb.selectorLabels" . | nindent 6 }}
{{- end -}}